# Generated by Django 4.0.2 on 2022-02-14 00:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Customer name', max_length=40)),
                ('phone', models.IntegerField(help_text='Phone Number')),
                ('address', models.CharField(help_text='Mailing Address', max_length=40)),
                ('city', models.CharField(help_text='City', max_length=20)),
                ('state', models.CharField(help_text='State', max_length=2)),
                ('zip_code', models.IntegerField(help_text='Zip Code')),
                ('email_add', models.EmailField(help_text='Email Address', max_length=25)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='dog_breeds',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('breed_name', models.CharField(help_text='Enter a breed name', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='dog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dog_name', models.CharField(help_text='Dog Name', max_length=20)),
                ('dog_color', models.CharField(help_text='Dog Fur Color', max_length=10)),
                ('dog_age', models.IntegerField(help_text='Dog Age')),
                ('dog_weight', models.IntegerField(help_text='Dog Weight')),
                ('dog_photo', models.ImageField(upload_to=None)),
                ('dog_breed', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.dog_breeds')),
                ('dog_owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.customer')),
            ],
        ),
        migrations.CreateModel(
            name='customer_notes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_made', models.DateTimeField(auto_now_add=True)),
                ('customer_note', models.TextField(help_text='Enter Note Comments')),
                ('made_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('note_owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.customer')),
            ],
            options={
                'ordering': ['date_made'],
            },
        ),
    ]
