# Generated by Django 4.0.2 on 2022-02-14 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_customer_notes_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer_notes',
            options={'ordering': ['date_made']},
        ),
    ]
