# Generated by Django 4.0.2 on 2022-02-14 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_customer_notes_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer_notes',
            name='note_subject',
            field=models.CharField(blank=True, help_text='Note Subject', max_length=40),
        ),
    ]
