# Generated by Django 4.0.2 on 2022-02-26 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_announcement'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dog',
            options={'ordering': ['dog_name']},
        ),
        migrations.AlterField(
            model_name='dog',
            name='dog_photo',
            field=models.ImageField(blank=True, upload_to=None),
        ),
    ]
